# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven (CloudHub-build and deploy)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Extract values Package
      run: |
        applicationName=$(grep -oPm1 "(?<=<artifactId>)[^<]+" pom.xml)
        applicationVersion=$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml)
        applicationJarPath=`echo "target/${applicationName}-${applicationVersion}-mule-application.jar"`

        echo "applicationName from pom.xml: $applicationName"
        echo "version from pom.xml: $applicationVersion"
        echo "jarPath from pom.xml: $applicationJarPath"

        export APPLICATION_NAME=$applicationName
        export APPLICATION_VERSION=$applicationVersion
        export APPLICATION_JAR_PATH=$applicationJarPath

   - name: Build Package
     run: mvn clean -B package  -s maven/settings.xml
 

   
      
#      env:
#        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
#        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
#        PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
#        PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
#        SANDBOX_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}
#        SANDBOX_CLIENT_SECRET: ${{ secrets.SANDBOX_CLIENT_SECRET }} 
    - name: Verify vars
      run: |
        echo "applicationName from pom.xml: $APPLICATION_NAME"
        echo "version from pom.xml: $APPLICATION_VERSION"
        echo "jarPath from pom.xml: $APPLICATION_JAR_PATH"    
